[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/syl20bnr/spacemacs.git"
    refreshPeriod = "168h"
[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/jorik.zsh-theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/jcronenberg/dotfiles/master/various/jorik.zsh-theme"
    refreshPeriod = "168h"
[".config/awesome/lain"]
    type = "git-repo"
    url = "https://github.com/lcpz/lain.git"
    refreshPeriod = "168h"
[".config/awesome/freedesktop"]
    type = "git-repo"
    url = "https://github.com/lcpz/awesome-freedesktop.git"
    refreshPeriod = "168h"
[".config/awesome/layout-machi"]
    type = "git-repo"
    url = "https://github.com/jcronenberg/layout-machi.git"
    refreshPeriod = "168h"
[".config/awesome/machina"]
    type = "git-repo"
    url = "https://github.com/jcronenberg/awesomewm-machina.git"
    refreshPeriod = "168h"
[".tmux_themes/nord-tmux"]
    type = "git-repo"
    url = "https://github.com/arcticicestudio/nord-tmux.git"
    refreshPeriod = "168h"
[".fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"
