[colors.bright]
black = "#6D7070"
blue = "#3daee9"
cyan = "#d8fdfc"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.cursor]
cursor = "#d8fdfc"
text = "#000000"

[colors.normal]
black = "#0d0d0d"
blue = "#387aaa"
cyan = "#b3ebe2"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#ffcc00"

[colors.primary]
background = "#000000"
foreground = "#EBEBEB"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.6
title = "Alacritty"
